name: "Hello boy"

on: 
  workflow_dispatch:
    inputs:
      Your_name:
        description: "Enter your name here"
        required: true

jobs:
  call_docker_action:
    name: call_docker_action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3
      - name: calling docker 
        uses: ./github/actions/hello
        with: 
          name: ${{ inputs.Your_name }}